# Generated by Django 3.1.2 on 2022-02-07 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_pricelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountState',
            fields=[
                ('userid', models.OneToOneField(db_column='UserID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='polls.userinfo')),
                ('total_balance', models.IntegerField()),
                ('total_deposit', models.IntegerField()),
                ('total_buy', models.IntegerField()),
                ('total_cash', models.IntegerField()),
                ('sell_count', models.IntegerField()),
                ('total_profit', models.IntegerField()),
                ('total_profit_percent', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'account_state',
                'managed': False,
            },
        ),
    ]
