# Generated by Django 3.1.2 on 2022-02-16 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_accountstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessKey',
            fields=[
                ('userid', models.OneToOneField(db_column='UserID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='polls.userinfo')),
                ('upbit_secret_key', models.CharField(max_length=40)),
                ('upbit_access_key', models.CharField(max_length=40)),
                ('slack_token', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'access_key',
                'managed': False,
            },
        ),
    ]
